# Eigenvalue dan Eigenvector
## **1. Definisi Eigenvalue dan Eigenvector**

Eigenvalue dan eigenvector adalah konsep penting dalam aljabar linear, terutama digunakan dalam banyak bidang seperti fisika, teknik, pembelajaran mesin, dan lain-lain.

Ketika sebuah **matriks linear $A$** mengalikan sebuah **vektor $\vec{v}$**, biasanya hasilnya adalah vektor baru dengan arah dan panjang berbeda. Namun, dalam **kasus khusus**, ada vektor-vektor tertentu di mana hasil perkalian hanya mengubah panjangnya saja, tidak arah.



$$
A \vec{v} = \lambda \vec{v}
$$


Artinya, mengalikan matriks $( A )$ dengan vektor $( \vec{v} )$ akan menghasilkan vektor baru yang searah (atau berlawanan arah jika $( \lambda )$ negatif) dengan $( \vec{v})$  itu sendiri.


* $\lambda$ disebut **eigenvalue** (nilai eigen)
* $\vec{v} \neq \vec{0}$ disebut **eigenvector**



## **2. Mencari Eigenvalue dan Eigenvector dari Matriks**

Kita diberikan matriks:

$$
A = \begin{bmatrix} 2 & 1 \\ 1 & 2 \end{bmatrix}
$$

**Langkah 1: Mencari eigenvalue**

Gunakan determinan dari $A - \lambda I$:

$$
\det(A - \lambda I) = 0
\Rightarrow
\det \left( \begin{bmatrix} 2 - \lambda & 1 \\ 1 & 2 - \lambda \end{bmatrix} \right) = 0
$$

Hitung determinan:

$$
(2 - \lambda)^2 - 1 = 0
\Rightarrow \lambda^2 - 4\lambda + 3 = 0
$$

Faktorkan:

$$
(\lambda - 1)(\lambda - 3) = 0
\Rightarrow \lambda = 1, \; \lambda = 3
$$

Jadi, matriks ini memiliki **dua eigenvalue: 1 dan 3**.


**Langkah 2: Mencari eigenvector**

 a. Untuk $\lambda = 1$:

$$
(A - I) \vec{v} = 0
\Rightarrow
\left( \begin{bmatrix} 2 & 1 \\ 1 & 2 \end{bmatrix} - \begin{bmatrix} 1 & 0 \\ 0 & 1 \end{bmatrix} \right)
= \begin{bmatrix} 1 & 1 \\ 1 & 1 \end{bmatrix}
$$

Mencari solusi:

$$
\begin{bmatrix} 1 & 1 \\ 1 & 1 \end{bmatrix} \begin{bmatrix} x \\ y \end{bmatrix} = \begin{bmatrix} 0 \\ 0 \end{bmatrix}
\Rightarrow x + y = 0 \Rightarrow y = -x
$$

Jadi eigenvector-nya (bisa dikalikan skalar bebas):

$$
\vec{v}_1 = \begin{bmatrix} 1 \\ -1 \end{bmatrix}
$$



b. Untuk $\lambda = 3$:

$$
(A - 3I) \vec{v} = 0 \Rightarrow
\begin{bmatrix} -1 & 1 \\ 1 & -1 \end{bmatrix}
\begin{bmatrix} x \\ y \end{bmatrix} = \begin{bmatrix} 0 \\ 0 \end{bmatrix}
\Rightarrow -x + y = 0 \Rightarrow y = x
$$

Maka:

$$
\vec{v}_2 = \begin{bmatrix} 1 \\ 1 \end{bmatrix}
$$



## **3. Menormalkan Vektor (Ortonormalisasi)**

**Tujuan:** Ubah vektor sehingga panjangnya = 1, tanpa mengubah arahnya.

Panjang vektor:

$$
\|\vec{v}\| = \sqrt{x^2 + y^2}
$$

a. Normalkan $\vec{v}_1 = \begin{bmatrix} 1 \\ -1 \end{bmatrix}$

$$
\|\vec{v}_1\| = \sqrt{1^2 + (-1)^2} = \sqrt{2}
\Rightarrow \hat{v}_1 = \frac{1}{\sqrt{2}} \begin{bmatrix} 1 \\ -1 \end{bmatrix}
$$

b. Normalkan $\vec{v}_2 = \begin{bmatrix} 1 \\ 1 \end{bmatrix}$

$$
\|\vec{v}_2\| = \sqrt{1^2 + 1^2} = \sqrt{2}
\Rightarrow \hat{v}_2 = \frac{1}{\sqrt{2}} \begin{bmatrix} 1 \\ 1 \end{bmatrix}
$$



## **4. Ortogonal dan Ortonormal**

* **Ortogonal**: Dua vektor saling tegak lurus jika dot product-nya nol.
* **Ortonormal**: Dua vektor yang ortogonal dan panjangnya 1.

Cek:

$$
\vec{v}_1 \cdot \vec{v}_2 = (1)(1) + (-1)(1) = 1 - 1 = 0
\Rightarrow \text{ortogonal}
$$

Karena sudah dinormalisasi → ortonormal:

$$
\hat{v}_1 = \frac{1}{\sqrt{2}} \begin{bmatrix} 1 \\ -1 \end{bmatrix},
\quad
\hat{v}_2 = \frac{1}{\sqrt{2}} \begin{bmatrix} 1 \\ 1 \end{bmatrix}
$$




In [7]:
import numpy as np

# Matriks A
A = np.array([[2, 1],
              [1, 2]])

# Langkah 1: Cari eigenvalue dan eigenvector
eigenvalues, eigenvectors = np.linalg.eig(A)

print("Eigenvalues:")
print(eigenvalues)

print("\nEigenvectors (kolom-kolomnya):")
print(eigenvectors)

# Langkah 2: Normalisasi vektor (hasil dari numpy.linalg.eig sudah ter-normalisasi, tapi kita ulangi manual)
def normalize(v):
    return v / np.linalg.norm(v)

print("\nVektor ortonormal:")
for vec in eigenvectors.T:  # Transpose agar tiap vektor jadi baris
    print(normalize(vec))

# Langkah 3: Cek ortogonalitas (dot product antar vektor)
dot_product = np.dot(eigenvectors[:,0], eigenvectors[:,1])
print("\nDot product vektor eigen ke-1 dan ke-2 (harusnya 0 jika ortogonal):", dot_product)


Eigenvalues:
[3. 1.]

Eigenvectors (kolom-kolomnya):
[[ 0.70710678 -0.70710678]
 [ 0.70710678  0.70710678]]

Vektor ortonormal:
[0.70710678 0.70710678]
[-0.70710678  0.70710678]

Dot product vektor eigen ke-1 dan ke-2 (harusnya 0 jika ortogonal): 0.0


In [6]:
import numpy as np

# --- Matriks A ---
A = np.array([[2, 1],
              [1, 2]])

print("Matriks A:")
print(A)

# --- Langkah 1: Mencari Eigenvalue dan Eigenvector ---
eigenvalues, eigenvectors = np.linalg.eig(A)

print("\nEigenvalues (nilai eigen):")
print(eigenvalues)

print("\nEigenvectors (setiap kolom adalah satu eigenvector):")
print(eigenvectors)

# --- Langkah 2: Normalisasi Vektor Eigen (agar panjang = 1) ---
def normalize(v):
    return v / np.linalg.norm(v)

# Normalisasi masing-masing eigenvector
v1 = eigenvectors[:, 0]
v2 = eigenvectors[:, 1]

v1_normalized = normalize(v1)
v2_normalized = normalize(v2)

print("\nEigenvector 1 setelah dinormalisasi:")
print(v1_normalized)

print("\nEigenvector 2 setelah dinormalisasi:")
print(v2_normalized)

# --- Langkah 3: Cek Ortogonalitas ---
dot_product = np.dot(v1_normalized, v2_normalized)
print("\nDot product antara dua eigenvector (harusnya ≈ 0 jika ortogonal):")
print(dot_product)

# --- Langkah 4: Cek apakah ortonormal ---
print("\nPanjang masing-masing vektor (harusnya ≈ 1 jika ortonormal):")
print("||v1|| =", np.linalg.norm(v1_normalized))
print("||v2|| =", np.linalg.norm(v2_normalized))


Matriks A:
[[2 1]
 [1 2]]

Eigenvalues (nilai eigen):
[3. 1.]

Eigenvectors (setiap kolom adalah satu eigenvector):
[[ 0.70710678 -0.70710678]
 [ 0.70710678  0.70710678]]

Eigenvector 1 setelah dinormalisasi:
[0.70710678 0.70710678]

Eigenvector 2 setelah dinormalisasi:
[-0.70710678  0.70710678]

Dot product antara dua eigenvector (harusnya ≈ 0 jika ortogonal):
0.0

Panjang masing-masing vektor (harusnya ≈ 1 jika ortonormal):
||v1|| = 1.0
||v2|| = 1.0
