# **INVERS MATRIKS**
## **Definisi Matriks Invers**
Matriks invers adalah matriks yang, jika dikalikan dengan matriks asalnya, menghasilkan matriks identitas. Jika A adalah matriks persegi (memiliki jumlah baris dan kolom yang sama), maka invers dari A, yang ditulis sebagai $A^{-1}$, memenuhi:

$$ A \times A^{-1} = A^{-1} \times A = I $$

di mana $I$ adalah matriks identitas, yaitu matriks dengan elemen diagonal utama bernilai 1 dan elemen lainnya bernilai 0.


## **Syarat Matriks Memiliki Invers**
Suatu matriks $A$ bisa dibalik (memiliki invers) jika dan hanya jika:

1. **Matriks Persegi**  
   - Matriks harus memiliki jumlah baris dan kolom yang sama (matriks $n \times n$).

2. **Determinan Tidak Nol**  
   - Determinan matriks tidak boleh nol ($\det(A) \neq 0$). Jika determinan nol, maka matriks disebut *singular* dan tidak memiliki invers.

3. **Rang Matriks Sama dengan Ordo**  
   - Rang (jumlah baris atau kolom yang tidak nol setelah eliminasi Gauss) dari matriks harus sama dengan ordo matriksnya ($\text{rank}(A) = n$).

Jika ketiga syarat ini terpenuhi, maka matriks memiliki invers, dan kita bisa menghitungnya menggunakan metode seperti:
- Metode Adjoin
- Metode Eliminasi Gauss-Jordan
- Faktorisasi LU


## **Matriks 3 Persamaan**
$$
\begin{cases}
2x_1 - x_2 + 3x_3 = 2 \\
x_1 + 2x_2 - 2x_3 = 1 \\
3x_1 - 3x_2 + 4x_3 = 3
\end{cases}
$$


## **Langkah Penyelesaian**
### **Langkah 1: Menuliskan Matriks Augmented [A | I]**
Matriks yang diberikan adalah:

$
A =
\begin{bmatrix}
2 & -1 & 3 \\
1 & 2 & -2 \\
3 & -3 & 4
\end{bmatrix}
$

Matriks identitas $( I )$ yang berukuran sama (3×3) adalah:

$
I =
\begin{bmatrix}
1 & 0 & 0 \\
0 & 1 & 0 \\
0 & 0 & 1
\end{bmatrix}
$

Gabungkan kedua matriks tersebut menjadi matriks augmented $( [A | I] )$:

$$
\begin{bmatrix}
2  & -1  &  3  & |  1  &  0  &  0  \\
1  &  2  & -2  & |  0  &  1  &  0  \\
3  & -3  &  4  & |  0  &  0  &  1  
\end{bmatrix}
$$

Tujuan kita adalah mengubah bagian kiri menjadi matriks identitas, sehingga bagian kanan menjadi matriks invers.


In [ ]:
import numpy as np

def print_matrix(title, M):
    print(title)
    print(np.array(M))
    print("\n")

# Langkah 1: Definisikan matriks A dan identitas I
A = np.array([[2, -1, 3],
              [1, 2, -2],
              [3, -3, 4]], dtype=float)
I = np.identity(3, dtype=float)
augmented = np.hstack((A, I))
print_matrix("Langkah 1: Matriks Augmented [A | I]", augmented)

Langkah 1: Matriks Augmented [A | I]
[[ 2. -1.  3.  1.  0.  0.]
 [ 1.  2. -2.  0.  1.  0.]
 [ 3. -3.  4.  0.  0.  1.]]




### **Langkah 2: Membuat Elemen (1,1) Menjadi 1**

Elemen pertama pada baris pertama adalah 2, jadi kita bagi seluruh baris pertama dengan 2 agar elemen (1,1) menjadi 1:


- Matriks Awal:


$
A =
\begin{bmatrix}
2 & -1 & 3 & 1 & 0 & 0 \\
1 & 2 & -2 & 0 & 1 & 0 \\
3 & -3 & 4 & 0 & 0 & 1
\end{bmatrix}
$



- Menjadikan Elemen (1,1) = 1

Gunakan operasi:

$
R_1 = \frac{1}{2} R_1
$

Sehingga setiap elemen pada $( R_1 )$ berubah menjadi:

$$
\begin{aligned}
R_1(1,1) &= \frac{2}{2} = 1 \\
R_1(1,2) &= \frac{-1}{2} = -\frac{1}{2} \\
R_1(1,3) &= \frac{3}{2} \\
R_1(1,4) &= \frac{1}{2} \\
R_1(1,5) &= \frac{0}{2} = 0 \\
R_1(1,6) &= \frac{0}{2} = 0
\end{aligned}
$$

Matriks Setelah Operasi:

$
A =
\begin{bmatrix}
1 & -\frac{1}{2} & \frac{3}{2} & \frac{1}{2} & 0 & 0 \\
1 & 2 & -2 & 0 & 1 & 0 \\
3 & -3 & 4 & 0 & 0 & 1
\end{bmatrix}
$




In [3]:
import numpy as np

# Matriks awal
a = np.array([
    [2, -1, 3, 1, 0, 0],
    [1,  2, -2, 0, 1, 0],
    [3, -3,  4, 0, 0, 1]
], dtype=float)

# Operasi: R1 = (1/2) * R1
a[0] = a[0] / 2

# Cetak hasil setelah operasi
print("Matriks setelah operasi:")
print(a)

Matriks setelah operasi:
[[ 1.  -0.5  1.5  0.5  0.   0. ]
 [ 1.   2.  -2.   0.   1.   0. ]
 [ 3.  -3.   4.   0.   0.   1. ]]


### **Langkah 3: Membuat Elemen (2,1) dan (3,1) Menjadi 0**
Supaya kolom pertama hanya memiliki angka 1 di posisi (1,1) dan nol di bawahnya, kita lakukan operasi baris berikut:

$
A =
\begin{bmatrix}
1 & -\frac{1}{2} & \frac{3}{2} & \frac{1}{2} & 0 & 0 \\
1 & 2 & -2 & 0 & 1 & 0 \\
3 & -3 & 4 & 0 & 0 & 1
\end{bmatrix}
$



- Menghilangkan Elemen (2,1)
Gunakan operasi:
$
R_2 = R_2 - R_1
$


$$
\begin{aligned}
R_2(1,1) &= 1 - 1 = 0 \\
R_2(1,2) &= 2 - \left(-\frac{1}{2}\right) = 2 + \frac{1}{2} = \frac{5}{2} \\
R_2(1,3) &= -2 - \frac{3}{2} = -\frac{7}{2} \\
R_2(1,4) &= 0 - \frac{1}{2} = -\frac{1}{2} \\
R_2(1,5) &= 1 - 0 = 1 \\
R_2(1,6) &= 0 - 0 = 0
\end{aligned}
$$

Sehingga baris kedua setelah operasi menjadi:

$$
\begin{bmatrix}
0 & \frac{5}{2} & -\frac{7}{2} & -\frac{1}{2} & 1 & 0
\end{bmatrix}
$$

- Menghilangkan Elemen (3,1)
Gunakan operasi:
$
R_3 = R_3 - 3R_1
$

$$
\begin{aligned}
R_3(1,1) &= 3 - 3(1) = 0 \\
R_3(1,2) &= -3 - 3\left(-\frac{1}{2}\right) = -3 + \frac{3}{2} = -\frac{3}{2} \\
R_3(1,3) &= 4 - 3\left(\frac{3}{2}\right) = 4 - \frac{9}{2} = -\frac{1}{2} \\
R_3(1,4) &= 0 - 3\left(\frac{1}{2}\right) = -\frac{3}{2} \\
R_3(1,5) &= 0 - 3(0) = 0 \\
R_3(1,6) &= 1 - 3(0) = 1
\end{aligned}
$$

Sehingga baris ketiga setelah operasi menjadi:

$$
\begin{bmatrix}
0 & -\frac{3}{2} & -\frac{1}{2} & -\frac{3}{2} & 0 & 1
\end{bmatrix}
$$

- Matriks Setelah Operasi

$$
\begin{bmatrix}
1 & -\frac{1}{2} & \frac{3}{2} & \frac{1}{2} & 0 & 0 \\
0 & \frac{5}{2} & -\frac{7}{2} & -\frac{1}{2} & 1 & 0 \\
0 & -\frac{3}{2} & -\frac{1}{2} & -\frac{3}{2} & 0 & 1
\end{bmatrix}
$$


In [6]:
import numpy as np

# Matriks awal (gabungan matriks A dan identitas I)
A = np.array([
    [1, -1/2, 3/2, 1/2, 0, 0],
    [1, 2, -2, 0, 1, 0],
    [3, -3, 4, 0, 0, 1]
], dtype=float)

print("Matriks awal:")
print(A)

# Menghilangkan elemen (2,1): R2 = R2 - R1
A[1] = A[1] - A[0]

# Menghilangkan elemen (3,1): R3 = R3 - 3R1
A[2] = A[2] - 3 * A[0]

print("\nMatriks setelah operasi baris:")
print(A)

Matriks awal:
[[ 1.  -0.5  1.5  0.5  0.   0. ]
 [ 1.   2.  -2.   0.   1.   0. ]
 [ 3.  -3.   4.   0.   0.   1. ]]

Matriks setelah operasi baris:
[[ 1.  -0.5  1.5  0.5  0.   0. ]
 [ 0.   2.5 -3.5 -0.5  1.   0. ]
 [ 0.  -1.5 -0.5 -1.5  0.   1. ]]


### **Langkah 4: Membuat Elemen (2,2) Menjadi 1**


Matriks sebelum operasi:

$$
A =
\begin{bmatrix}
1 & -\frac{1}{2} & \frac{3}{2} & \frac{1}{2} & 0 & 0 \\
0 & \frac{5}{2} & -\frac{7}{2} & -\frac{1}{2} & 1 & 0 \\
0 & -\frac{3}{2} & -\frac{1}{2} & -\frac{3}{2} & 0 & 1
\end{bmatrix}
$$

Untuk membuat elemen $(2,2)$ menjadi 1, kita bagi seluruh baris ke-2 dengan nilai elemen $(2,2)$, yaitu $\frac{5}{2}$.

Operasi yang dilakukan:
$
R_2 = \frac{R_2}{\frac{5}{2}}
$

Perhitungan untuk baris ke-2:

$$
\begin{aligned}
R_2(1,2) &= \frac{5}{2} \times \frac{2}{5} = 1 \\
R_2(1,3) &= -\frac{7}{2} \times \frac{2}{5} = -\frac{14}{10} = -\frac{7}{5} \\
R_2(1,4) &= -\frac{1}{2} \times \frac{2}{5} = -\frac{2}{10} = -\frac{1}{5} \\
R_2(1,5) &= 1 \times \frac{2}{5} = \frac{2}{5} \\
R_2(1,6) &= 0 \times \frac{2}{5} = 0
\end{aligned}
$$

Matriks setelah operasi:

$$
A =
\begin{bmatrix}
1 & -\frac{1}{2} & \frac{3}{2} & \frac{1}{2} & 0 & 0 \\
0 & 1 & -\frac{7}{5} & -\frac{1}{5} & \frac{2}{5} & 0 \\
0 & -\frac{3}{2} & -\frac{1}{2} & -\frac{3}{2} & 0 & 1
\end{bmatrix}
$$



In [7]:
import numpy as np

# Matriks awal setelah langkah 3
A = np.array([
    [1, -1/2,  3/2,  1/2,  0, 0],
    [0,  5/2, -7/2, -1/2,  1, 0],
    [0, -3/2, -1/2, -3/2,  0, 1]
], dtype=np.float64)

# Membagi baris ke-2 dengan elemen (2,2) untuk membuatnya menjadi 1
A[1] = A[1] / A[1, 1]

# Cetak hasil matriks setelah operasi
np.set_printoptions(suppress=True, precision=5)  # Supaya tampilan lebih rapi
print("Matriks setelah langkah 4:")
print(A)


Matriks setelah langkah 4:
[[ 1.  -0.5  1.5  0.5  0.   0. ]
 [ 0.   1.  -1.4 -0.2  0.4  0. ]
 [ 0.  -1.5 -0.5 -1.5  0.   1. ]]


### **Langkah 5: Membuat Elemen (1,2) dan (3,2) Menjadi 0**

Pada langkah ini, kita akan mengubah elemen pada posisi $(1,2)$ dan $(3,2)$ menjadi nol, agar kolom ke-2 hanya memiliki angka 1 di posisi  $(2,2)$ dan nol di atas serta di bawahnya.

- Matriks Sebelum Operasi

$$
A =
\begin{bmatrix}
1 & -\frac{1}{2} & \frac{3}{2} & \frac{1}{2} & 0 & 0 \\
0 & 1 & -\frac{7}{5} & -\frac{1}{5} & \frac{2}{5} & 0 \\
0 & -\frac{3}{2} & -\frac{1}{2} & -\frac{3}{2} & 0 & 1
\end{bmatrix}
$$


- Menghilangkan Elemen (1,2)

Gunakan operasi baris:

$
R_1 = R_1 + \frac{1}{2} R_2
$

Perhitungan setiap elemen pada baris pertama:

$$
\begin{aligned}
R_1(1,1) &= 1 + \frac{1}{2} (0) = 1 \\
R_1(1,2) &= -\frac{1}{2} + \frac{1}{2} (1) = 0 \\
R_1(1,3) &= \frac{3}{2} + \frac{1}{2} (-\frac{7}{5}) = \frac{4}{5} \\
R_1(1,4) &= \frac{1}{2} + \frac{1}{2} (-\frac{1}{5}) = \frac{2}{5} \\
R_1(1,5) &= 0 + \frac{1}{2} (\frac{2}{5}) = \frac{1}{5} \\
R_1(1,6) &= 0 + \frac{1}{2} (0) = 0
\end{aligned}
$$

Hasil baris pertama setelah operasi:

$$
\begin{bmatrix} 1 & 0 & \frac{4}{5} & \frac{2}{5} & \frac{1}{5} & 0 \end{bmatrix}
$$

- Menghilangkan Elemen (3,2)

Gunakan operasi baris:

$
R_3 = R_3 + \frac{3}{2} R_2
$

Perhitungan setiap elemen pada baris ketiga:

$$
\begin{aligned}
R_3(3,1) &= 0 + \frac{3}{2} (0) = 0 \\
R_3(3,2) &= -\frac{3}{2} + \frac{3}{2} (1) = 0 \\
R_3(3,3) &= -\frac{1}{2} + \frac{3}{2} (-\frac{7}{5}) = -\frac{13}{5} \\
R_3(3,4) &= -\frac{3}{2} + \frac{3}{2} (-\frac{1}{5}) = -\frac{9}{5} \\
R_3(3,5) &= 0 + \frac{3}{2} (\frac{2}{5}) = \frac{3}{5} \\
R_3(3,6) &= 1 + \frac{3}{2} (0) = 1
\end{aligned}
$$

Hasil baris ketiga setelah operasi:

$$
\begin{bmatrix} 0 & 0 & -\frac{13}{5} & -\frac{9}{5} & \frac{3}{5} & 1 \end{bmatrix}
$$

Sehingga matriks setelah langkah ini menjadi:

$$
\begin{bmatrix}
1 & 0 & \frac{4}{5} & \frac{2}{5} & \frac{1}{5} & 0 \\
0 & 1 & -\frac{7}{5} & -\frac{1}{5} & \frac{2}{5} & 0 \\
0 & 0 & -\frac{13}{5} & -\frac{9}{5} & \frac{3}{5} & 1
\end{bmatrix}
$$

In [8]:
import numpy as np

# Matriks awal sebelum langkah 5
A = np.array([
    [1, -1/2,  3/2,  1/2,  0, 0],
    [0,  1,   -7/5, -1/5,  2/5, 0],
    [0, -3/2, -1/2, -3/2,  0, 1]
], dtype=float)

# Operasi untuk membuat elemen (1,2) menjadi 0
A[0] = A[0] + (1/2) * A[1]

# Operasi untuk membuat elemen (3,2) menjadi 0
A[2] = A[2] + (3/2) * A[1]

# Menampilkan hasil setelah langkah 5
print("Matriks setelah Langkah 5:")
print(A)

Matriks setelah Langkah 5:
[[ 1.   0.   0.8  0.4  0.2  0. ]
 [ 0.   1.  -1.4 -0.2  0.4  0. ]
 [ 0.   0.  -2.6 -1.8  0.6  1. ]]



### **Langkah 6: Membuat Elemen (3,3) Menjadi 1**

Untuk membuat elemen $(3,3)$ menjadi 1, kita bagi seluruh baris ketiga ($R_3$) dengan elemen $(3,3)$ yang bernilai $-\frac{13}{5}$:

$
R_3 = R_3 \div \left(-\frac{13}{5}\right)
$

$$
\begin{aligned}
R_3(3,3) &= \frac{-13}{5} \div \left(-\frac{13}{5}\right) = 1 \\  
R_3(3,4) &= \frac{-9}{5} \div \left(-\frac{13}{5}\right) = \frac{9}{13} \\  
R_3(3,5) &= \frac{3}{5} \div \left(-\frac{13}{5}\right) = -\frac{3}{13} \\  
R_3(3,6) &= 1 \div \left(-\frac{13}{5}\right) = -\frac{5}{13}  
\end{aligned}
$$

Sehingga matriks setelah langkah ini menjadi:

$$
\begin{bmatrix}
1 & 0 & \frac{4}{5} & \frac{2}{5} & \frac{1}{5} & 0 \\
0 & 1 & -\frac{7}{5} & -\frac{1}{5} & \frac{2}{5} & 0 \\
0 & 0 & 1 & \frac{9}{13} & -\frac{3}{13} & -\frac{5}{13}
\end{bmatrix}
$$


In [9]:
import numpy as np

# Matriks setelah langkah 5
A = np.array([
    [1, 0, 4/5, 2/5, 1/5, 0],
    [0, 1, -7/5, -1/5, 2/5, 0],
    [0, 0, -13/5, -9/5, 3/5, 1]
], dtype=float)

# Membagi baris ke-3 dengan elemen (3,3) agar menjadi 1
A[2] = A[2] / A[2, 2]

print("Matriks setelah Langkah 6:")
print(A)

Matriks setelah Langkah 6:
[[ 1.       0.       0.8      0.4      0.2      0.     ]
 [ 0.       1.      -1.4     -0.2      0.4      0.     ]
 [-0.      -0.       1.       0.69231 -0.23077 -0.38462]]


### **Langkah 7: Membuat Elemen (1,3) dan (2,3) Menjadi 0**

Untuk membuat elemen $(1,3)$ dan $(2,3)$ menjadi nol, kita gunakan operasi:

$
R_1 = R_1 - \left(\frac{4}{5} R_3 \right)
$

$
R_2 = R_2 + \left(\frac{7}{5} R_3 \right)
$

- Perhitungan untuk $R_1$:

$$
\begin{aligned}
R_1(1,3) &= \frac{4}{5} - \frac{4}{5} (1) = 0 \\  
R_1(1,4) &= \frac{2}{5} - \frac{4}{5} \times \frac{9}{13} = \frac{2}{13} \\  
R_1(1,5) &= \frac{1}{5} - \frac{4}{5} \times \frac{-3}{13} = \frac{17}{65} \\  
R_1(1,6) &= 0 - \frac{4}{5} \times \frac{-5}{13} = \frac{4}{13}  
\end{aligned}
$$

Sehingga baris pertama setelah operasi menjadi:

$$
\begin{bmatrix}
1 & 0 & 0 & \frac{2}{13} & \frac{17}{65} & \frac{4}{13}
\end{bmatrix}
$$

- Perhitungan untuk $R_2$:

$$
\begin{aligned}
R_2(1,3) &= -\frac{7}{5} + \frac{7}{5} (1) = 0 \\  
R_2(1,4) &= -\frac{1}{5} + \frac{7}{5} \times \frac{9}{13} = \frac{10}{13} \\  
R_2(1,5) &= \frac{2}{5} + \frac{7}{5} \times \frac{-3}{13} = \frac{1}{13} \\  
R_2(1,6) &= 0 + \frac{7}{5} \times \frac{-5}{13} = -\frac{7}{13}
\end{aligned}
$$

Sehingga baris kedua setelah operasi menjadi:

$$
\begin{bmatrix}
0 & 1 & 0 & \frac{10}{13} & \frac{1}{13} & -\frac{7}{13}
\end{bmatrix}
$$



Matriks Setelah Langkah 7

$$
\begin{bmatrix}
1 & 0 & 0 & \frac{2}{13} & \frac{17}{65} & \frac{4}{13} \\
0 & 1 & 0 & \frac{10}{13} & \frac{1}{13} & -\frac{7}{13} \\
0 & 0 & 1 & \frac{9}{13} & -\frac{3}{13} & -\frac{5}{13}
\end{bmatrix}
$$

Matriks ini menunjukkan bahwa kita telah mendapatkan matriks identitas di sebelah kiri, sehingga matriks di sebelah kanan adalah invers dari matriks awal.




In [10]:
# Eliminasi elemen (1,3) dan (2,3) agar menjadi nol
A[0] = A[0] - A[0, 2] * A[2]
A[1] = A[1] - A[1, 2] * A[2]

print("Matriks setelah Langkah 7:")
print(A)

Matriks setelah Langkah 7:
[[ 1.       0.       0.      -0.15385  0.38462  0.30769]
 [ 0.       1.       0.       0.76923  0.07692 -0.53846]
 [-0.      -0.       1.       0.69231 -0.23077 -0.38462]]
