# **INVERS MATRIKS**
## **Definisi Matriks Invers**
Matriks invers adalah matriks yang, jika dikalikan dengan matriks asalnya, menghasilkan matriks identitas. Jika A adalah matriks persegi (memiliki jumlah baris dan kolom yang sama), maka invers dari A, yang ditulis sebagai $A^{-1}$, memenuhi:

$$ A \times A^{-1} = A^{-1} \times A = I $$

di mana $I$ adalah matriks identitas, yaitu matriks dengan elemen diagonal utama bernilai 1 dan elemen lainnya bernilai 0.


## **Syarat Matriks Memiliki Invers**
Suatu matriks $A$ bisa dibalik (memiliki invers) jika dan hanya jika:

1. **Matriks Persegi**  
   - Matriks harus memiliki jumlah baris dan kolom yang sama (matriks $n \times n$).

2. **Determinan Tidak Nol**  
   - Determinan matriks tidak boleh nol ($\det(A) \neq 0$). Jika determinan nol, maka matriks disebut *singular* dan tidak memiliki invers.

3. **Rang Matriks Sama dengan Ordo**  
   - Rang (jumlah baris atau kolom yang tidak nol setelah eliminasi Gauss) dari matriks harus sama dengan ordo matriksnya ($\text{rank}(A) = n$).

Jika ketiga syarat ini terpenuhi, maka matriks memiliki invers, dan kita bisa menghitungnya menggunakan metode seperti:
- Metode Adjoin
- Metode Eliminasi Gauss-Jordan
- Faktorisasi LU


## **Matriks 3 Persamaan**
$$
\begin{cases}
2x_1 - x_2 + 3x_3 = 2 \\
x_1 + 2x_2 - 2x_3 = 1 \\
3x_1 - 3x_2 + 4x_3 = 3
\end{cases}
$$


## **Langkah Penyelesaian**
### **Langkah 1: Menuliskan Matriks Augmented [A | I]**
Matriks yang diberikan adalah:
\
A =
\begin{bmatrix}
2 & -1 & 3 \\
1 & 2 & -2 \\
3 & -3 & 4
\end{bmatrix}


Matriks identitas \( I \) yang berukuran sama (3×3) adalah:

I =
\begin{bmatrix}
1 & 0 & 0 \\
0 & 1 & 0 \\
0 & 0 & 1
\end{bmatrix}
\
Gabungkan kedua matriks tersebut menjadi matriks augmented \( [A | I] \):


\begin{bmatrix}
2  & -1  &  3  & |  1  &  0  &  0  \\
1  &  2  & -2  & |  0  &  1  &  0  \\
3  & -3  &  4  & |  0  &  0  &  1  
\end{bmatrix}


Tujuan kita adalah mengubah bagian kiri menjadi matriks identitas, sehingga bagian kanan menjadi matriks invers.


In [10]:
import numpy as np

def print_matrix(title, M):
    print(title)
    print(np.array(M))
    print("\n")

# Langkah 1: Definisikan matriks A dan identitas I
A = np.array([[2, -1, 3],
              [1, 2, -2],
              [3, -3, 4]], dtype=float)
I = np.identity(3, dtype=float)
augmented = np.hstack((A, I))
print_matrix("Langkah 1: Matriks Augmented [A | I]", augmented)

Langkah 1: Matriks Augmented [A | I]
[[ 2. -1.  3.  1.  0.  0.]
 [ 1.  2. -2.  0.  1.  0.]
 [ 3. -3.  4.  0.  0.  1.]]




### **Langkah 2: Membuat Elemen (1,1) Menjadi 1**

Elemen pertama pada baris pertama adalah 2, jadi kita bagi seluruh baris pertama dengan 2 agar elemen (1,1) menjadi 1:

$$
R_1 = \frac{1}{2} R_1
$$


Hasilnya:


\begin{bmatrix}
1  & -\frac{1}{2}  &  \frac{3}{2}  & |  \frac{1}{2}  &  0  &  0  \\
1  &  2  & -2  & |  0  &  1  &  0  \\
3  & -3  &  4  & |  0  &  0  &  1  
\end{bmatrix}




In [11]:
# Langkah 2: Membuat elemen (1,1) menjadi 1
augmented[0] = augmented[0] / augmented[0, 0]
print_matrix("Langkah 2: Membuat elemen (1,1) menjadi 1", augmented)

Langkah 2: Membuat elemen (1,1) menjadi 1
[[ 1.  -0.5  1.5  0.5  0.   0. ]
 [ 1.   2.  -2.   0.   1.   0. ]
 [ 3.  -3.   4.   0.   0.   1. ]]




### **Langkah 3: Membuat Elemen (2,1) dan (3,1) Menjadi 0**
Supaya kolom pertama hanya memiliki angka 1 di posisi (1,1) dan nol di bawahnya, kita lakukan operasi baris berikut:

- Untuk menghilangkan angka 1 di posisi (2,1):

$$
R_2 = R_2 - R_1
$$

- Untuk menghilangkan angka 3 di posisi (3,1):

$$
R_3 = R_3 - 3R_1
$$


Setelah operasi ini:


\begin{bmatrix}
1  & -\frac{1}{2}  &  \frac{3}{2}  & |  \frac{1}{2}  &  0  &  0  \\
0  &  \frac{5}{2}  & -\frac{7}{2}  & |  -\frac{1}{2}  &  1  &  0  \\
0  & -\frac{3}{2}  &  \frac{5}{2}  & |  -\frac{3}{2}  &  0  &  1  
\end{bmatrix}



In [12]:
# Langkah 3: Membuat elemen (2,1) dan (3,1) menjadi 0
augmented[1] = augmented[1] - augmented[1, 0] * augmented[0]
augmented[2] = augmented[2] - augmented[2, 0] * augmented[0]
print_matrix("Langkah 3: Membuat elemen (2,1) dan (3,1) menjadi 0", augmented)

Langkah 3: Membuat elemen (2,1) dan (3,1) menjadi 0
[[ 1.  -0.5  1.5  0.5  0.   0. ]
 [ 0.   2.5 -3.5 -0.5  1.   0. ]
 [ 0.  -1.5 -0.5 -1.5  0.   1. ]]




### **Langkah 4: Membuat Elemen (2,2) Menjadi 1**
Bagian tengah (2,2) sekarang adalah \( \frac{5}{2} \), jadi kita bagi seluruh baris kedua dengan \( \frac{5}{2} \):

$$
R_2 = \frac{2}{5} R_2
$$

Hasilnya:


\begin{bmatrix}
1  & -\frac{1}{2}  &  \frac{3}{2}  & |  \frac{1}{2}  &  0  &  0  \\
0  & 1  & -\frac{7}{5}  & |  -\frac{1}{5}  &  \frac{2}{5}  &  0  \\
0  & -\frac{3}{2}  &  \frac{5}{2}  & |  -\frac{3}{2}  &  0  &  1  
\end{bmatrix}




In [13]:
# Langkah 4: Membuat elemen (2,2) menjadi 1
augmented[1] = augmented[1] / augmented[1, 1]
print_matrix("Langkah 4: Membuat elemen (2,2) menjadi 1", augmented)


Langkah 4: Membuat elemen (2,2) menjadi 1
[[ 1.  -0.5  1.5  0.5  0.   0. ]
 [ 0.   1.  -1.4 -0.2  0.4  0. ]
 [ 0.  -1.5 -0.5 -1.5  0.   1. ]]




### **Langkah 5: Membuat Elemen (1,2) dan (3,2) Menjadi 0**
Supaya hanya ada 1 di (2,2) dan nol di atas serta bawahnya, kita lakukan:

$$ R_1 = R_1 + \frac{1}{2} R_2 $$

$$ R_3 = R_3 + \frac{3}{2} R_2 $$

Hasilnya:


\begin{bmatrix}
1  &  0  &  \frac{8}{5}  & |  \frac{2}{10}  &  \frac{1}{5}  &  0  \\
0  &  1  & -\frac{7}{5}  & |  -\frac{1}{5}  &  \frac{2}{5}  &  0  \\
0  &  0  &  \frac{4}{10}  & |  -\frac{3}{10}  &  \frac{6}{10}  &  1  
\end{bmatrix}



In [14]:
# Langkah 5: Membuat elemen (1,2) dan (3,2) menjadi 0
augmented[0] = augmented[0] - augmented[0, 1] * augmented[1]
augmented[2] = augmented[2] - augmented[2, 1] * augmented[1]
print_matrix("Langkah 5: Membuat elemen (1,2) dan (3,2) menjadi 0", augmented)

Langkah 5: Membuat elemen (1,2) dan (3,2) menjadi 0
[[ 1.   0.   0.8  0.4  0.2  0. ]
 [ 0.   1.  -1.4 -0.2  0.4  0. ]
 [ 0.   0.  -2.6 -1.8  0.6  1. ]]





### **Langkah 6: Membuat Elemen (3,3) Menjadi 1**
Elemen (3,3) adalah $\frac{4}{10}$, jadi kita bagi seluruh baris ketiga dengan $\frac{4}{10}$:

$$
R_3 = \frac{10}{4} R_3
$$

Hasilnya:


\begin{bmatrix}
1  &  0  &  \frac{8}{5}  & |  \frac{2}{10}  &  \frac{1}{5}  &  0  \\
0  &  1  & -\frac{7}{5}  & |  -\frac{1}{5}  &  \frac{2}{5}  &  0  \\
0  &  0  &  1  & |  -\frac{3}{8}  &  \frac{3}{4}  &  \frac{5}{2}  
\end{bmatrix}



In [15]:
# Langkah 6: Membuat elemen (3,3) menjadi 1
augmented[2] = augmented[2] / augmented[2, 2]
print_matrix("Langkah 6: Membuat elemen (3,3) menjadi 1", augmented)

Langkah 6: Membuat elemen (3,3) menjadi 1
[[ 1.          0.          0.8         0.4         0.2         0.        ]
 [ 0.          1.         -1.4        -0.2         0.4         0.        ]
 [-0.         -0.          1.          0.69230769 -0.23076923 -0.38461538]]




### **Langkah 7: Membuat Elemen (1,3) dan (2,3) Menjadi 0**
Supaya kolom ketiga hanya memiliki angka 1 di (3,3) dan nol di atasnya, kita lakukan:

$$ R_1 = R_1 - \frac{8}{5} R_3 $$

$$ R_2 = R_2 + \frac{7}{5} R_3 $$

Hasil akhirnya:

\begin{bmatrix}
1  &  0  &  0  & |  2  & -1  & -1  \\
0  &  1  &  0  & |  3  & -2  & -1  \\
0  &  0  &  1  & |  -\frac{3}{8}  &  \frac{3}{4}  &  \frac{5}{2}  
\end{bmatrix}


Matriks kiri sudah menjadi identitas. Matriks di sebelah kanan adalah invers dari A:


$A^{-1}$=
\begin{bmatrix}
2  & -1  & -1  \\
3  & -2  & -1  \\
-\frac{3}{8}  & \frac{3}{4}  & \frac{5}{2}  
\end{bmatrix}


In [16]:
# Langkah 7: Membuat elemen (1,3) dan (2,3) menjadi 0
augmented[0] = augmented[0] - augmented[0, 2] * augmented[2]
augmented[1] = augmented[1] - augmented[1, 2] * augmented[2]
print_matrix("Langkah 7: Membuat elemen (1,3) dan (2,3) menjadi 0", augmented)

# Hasil akhir: Matriks invers
inverse_A = augmented[:, 3:]
print_matrix("Matriks Invers A", inverse_A)

Langkah 7: Membuat elemen (1,3) dan (2,3) menjadi 0
[[ 1.          0.          0.         -0.15384615  0.38461538  0.30769231]
 [ 0.          1.          0.          0.76923077  0.07692308 -0.53846154]
 [-0.         -0.          1.          0.69230769 -0.23076923 -0.38461538]]


Matriks Invers A
[[-0.15384615  0.38461538  0.30769231]
 [ 0.76923077  0.07692308 -0.53846154]
 [ 0.69230769 -0.23076923 -0.38461538]]


