## Jawaban

### Soal 1

Diketahui:

$$
A = \begin{bmatrix} 1 & -1 \\ 2 & 3 \end{bmatrix}, \quad
\vec{x} = \begin{bmatrix} 1 \\ 1 \end{bmatrix}, \quad
\vec{y} = \begin{bmatrix} -1 \\ 2 \end{bmatrix}
$$

Langkah-langkah:

Lakukan perkalian matriks $A$ dengan vektor $\vec{x}$:

$$
A\vec{x} = \begin{bmatrix} 1 & -1 \\ 2 & 3 \end{bmatrix}
\begin{bmatrix} 1 \\ 1 \end{bmatrix}
= \begin{bmatrix} 1(1) + (-1)(1) \\ 2(1) + 3(1) \end{bmatrix}
= \begin{bmatrix} 0 \\ 5 \end{bmatrix}
$$

Lanjutkan dengan perkalian matriks $A$ dengan vektor $\vec{y}$:

$$
A\vec{y} = \begin{bmatrix} 1 & -1 \\ 2 & 3 \end{bmatrix}
\begin{bmatrix} -1 \\ 2 \end{bmatrix}
= \begin{bmatrix} 1(-1) + (-1)(2) \\ 2(-1) + 3(2) \end{bmatrix}
= \begin{bmatrix} -3 \\ 4 \end{bmatrix}
$$


In [ ]:
import numpy as np

# Matriks dan vektor
A = np.array([[1, -1],
              [2,  3]])

x = np.array([[1],
              [1]])

y = np.array([[-1],
              [ 2]])

# Perkalian matriks dengan vektor
Ax = np.dot(A, x)
Ay = np.dot(A, y)

print("Hasil A * x:")
print(Ax)

print("\nHasil A * y:")
print(Ay)

Hasil A * x:
[[0]
 [5]]

Hasil A * y:
[[-3]
 [ 4]]


### Soal 2

Diketahui:

$$
A = \begin{bmatrix} 2 & 0 \\ -1 & 3 \end{bmatrix}
$$

Langkah-langkah:

Hitung $A\vec{x}$:

$$
A\vec{x} = \begin{bmatrix} 2 & 0 \\ -1 & 3 \end{bmatrix}
\begin{bmatrix} 1 \\ 1 \end{bmatrix}
= \begin{bmatrix} 2(1) + 0(1) \\ -1(1) + 3(1) \end{bmatrix}
= \begin{bmatrix} 2 \\ 2 \end{bmatrix}
$$

Hitung $A\vec{y}$:

$$
A\vec{y} = \begin{bmatrix} 2 & 0 \\ -1 & 3 \end{bmatrix}
\begin{bmatrix} -1 \\ 2 \end{bmatrix}
= \begin{bmatrix} 2(-1) + 0(2) \\ -1(-1) + 3(2) \end{bmatrix}
= \begin{bmatrix} -2 \\ 7 \end{bmatrix}
$$


In [ ]:
import numpy as np

# Matriks dan vektor
A = np.array([[ 2, 0],
              [-1, 3]])

x = np.array([[1],
              [1]])

y = np.array([[-1],
              [ 2]])

# Perkalian matriks dengan vektor
Ax = np.dot(A, x)
Ay = np.dot(A, y)

print("Hasil A * x:")
print(Ax)

print("\nHasil A * y:")
print(Ay)

Hasil A * x:
[[2]
 [2]]

Hasil A * y:
[[-2]
 [ 7]]


### Soal 5

Diketahui transformasi vektor standar sebagai berikut:

$$
\vec{i} = \begin{bmatrix} 1 \\ 0 \end{bmatrix} \rightarrow \begin{bmatrix} 1 \\ 2 \end{bmatrix}, \quad
\vec{j} = \begin{bmatrix} 0 \\ 1 \end{bmatrix} \rightarrow \begin{bmatrix} 0 \\ 2 \end{bmatrix}
$$

Langkah-langkah

Matriks transformasi $A$ dapat dibentuk dengan meletakkan hasil transformasi dari $\vec{i}$ dan $\vec{j}$ sebagai kolom-kolom dari matriks.

- Kolom pertama adalah hasil transformasi dari $\vec{i}$
- Kolom kedua adalah hasil transformasi dari $\vec{j}$


$$
A = \left[ T(\vec{i}) \quad T(\vec{j}) \right]
$$

Substitusikan hasil transformasi:

$$
A = \left[
\begin{array}{cc}
1 & 0 \\
2 & 2 \\
\end{array}
\right]
$$

Jadi, matriks transformasi yang sesuai adalah:

$$
A = \begin{bmatrix}
1 & 0 \\
2 & 2
\end{bmatrix}
$$


In [ ]:
import numpy as np

# Vektor standar (basis)
i = np.array([1, 0])
j = np.array([0, 1])

# Hasil transformasi vektor
Ti = np.array([1, 2])  # Transformasi dari i
Tj = np.array([0, 2])  # Transformasi dari j

# Matriks transformasi A dibentuk dari hasil transformasi vektor standar sebagai kolom
A = np.column_stack((Ti, Tj))

print("Matriks transformasi A:")
print(A)


Matriks transformasi A:
[[1 0]
 [2 2]]


### Soal 6

Diberikan sebuah sketsa transformasi dari unit square pada bidang koordinat. Diketahui bahwa titik asal berada di $(0,0)$, dan persegi satuan tersebut ditransformasikan menjadi jajaran genjang.

- Tujuan kita adalah untuk menentukan matriks transformasi $A$ yang mentransformasikan persegi satuan tersebut.

Langkah-langkah Penyelesaian

- Transformasi linier dapat direpresentasikan dalam bentuk matriks $A$, yang memetakan:

$$
A \vec{i} = \text{vektor hasil dari } \begin{bmatrix} 1 \\ 0 \end{bmatrix}
\quad \text{dan} \quad
A \vec{j} = \text{vektor hasil dari } \begin{bmatrix} 0 \\ 1 \end{bmatrix}
$$

Dari gambar, kita amati bahwa:

$$
\vec{i} = \begin{bmatrix} 1 \\ 0 \end{bmatrix} \rightarrow \begin{bmatrix} 1 \\ 1 \end{bmatrix}, \quad
\vec{j} = \begin{bmatrix} 0 \\ 1 \end{bmatrix} \rightarrow \begin{bmatrix} -1 \\ 1 \end{bmatrix}
$$


Maka, matriks transformasi $A$ adalah:

$$
A = \begin{bmatrix}
| & | \\
A\vec{i} & A\vec{j} \\
| & |
\end{bmatrix}
=
\begin{bmatrix}
1 & -1 \\
1 & 1
\end{bmatrix}
$$

Jawaban Akhir

$$
A = \begin{bmatrix}
1 & -1 \\
1 & 1
\end{bmatrix}
$$



In [ ]:
import numpy as np

# Definisi vektor basis awal
i_vector = np.array([1, 0])  # vektor i awal
j_vector = np.array([0, 1])  # vektor j awal

# Transformasi vektor
transformed_i = np.array([1, 1])  # hasil transformasi vektor i
transformed_j = np.array([-1, 1])  # hasil transformasi vektor j

# Matriks transformasi A
A = np.column_stack((transformed_i, transformed_j))

# Menampilkan hasil
print("Matriks transformasi A:")
print(A)

Matriks transformasi A:
[[ 1 -1]
 [ 1  1]]
